language: r
r: bioc-release
r: bioc-devel

cache: packages

before_install:    
  - tlmgr install tcolorbox

r_github_packages:
  - jimhester/covr
after_success:
  - Rscript -e 'library(covr);codecov()'
